[package]
name = "mailer"
version = "0.2.0"
authors = ["Mike Dilger <mike@optcomp.nz>"]
license = "MIT"

[dependencies.lettre]
version = "0.6"

[dependencies]
time = "0.1"
rustc-serialize = "0.3"
hyper = "0.9"
email = "0.0"
